language: java
jdk:
  - oraclejdk8
sudo: required
services:
  - docker
  - mysql
before_script:
  - mysql -u root -e "CREATE DATABASE grademaster;"
  - mysql -u root -e "CREATE USER 'dbuser'@'localhost' IDENTIFIED BY 'dbpassword';"
  - mysql -u root -e "GRANT ALL ON grademaster.* TO 'dbuser'@'localhost';"
  - docker-compose up -d activemq
notifications:
  email: false